[package]
name = "cli-bloom"
version = "0.2.0"
authors = ["Olivier Despesse <olived19@gmail.com>"]
edition = "2018"

[dependencies]
index-bloom = { git = "https://github.com/odespesse/index-bloom" }
clap = "2.33.0"
serde_json = "1.0"
